version: '3'
services:
  orientdb:
    image: orientdb:3.0.18
    container_name: "orientdb"
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'rootpwd'
    volumes:
      - ./orientdb/databases:/orientdb/databases
      - ./orientdb/backup:/orientdb/backup
      - ${PWD}/orientdb/config/orientdb-server-config.xml:/orientdb/config/orientdb-server-config.xml
