#!/bin/bash
if [ ! -d /tmp/spark-memory ]; then
  echo "Creating memory track dir"
  mkdir -p /tmp/spark-memory;
fi

sbt "runMain Main resources/configs/DOGS_exp/AC-19-5.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-6.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-7.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-8.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-9.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-10.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-11.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-12.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-13.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-14.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-15.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-16.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-17.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-18.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-19.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-20.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-21.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-22.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-23.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-24.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-25.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-26.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-27.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-28.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-29.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-30.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-31.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-32.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-33.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-34.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-35.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-36.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-37.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-38.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-39.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-40.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-41.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-42.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-43.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-44.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-45.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-46.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-47.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-48.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-49.conf"
sbt "runMain Main resources/configs/DOGS_exp/AC-19-50.conf"


