version: '3'
services:
  arangodb:
    image: arangodb/arangodb:3.6.0
    container_name: "arangodb"
    ports:
      - "8529:8529"
    environment:
      ARANGO_NO_AUTH: "1"
    volumes:
      - ../../../arangodb/data:/var/lib/arangodb3
